# This file should only contain setuptools related configuration to build the
# extension (i.e. arguments to setup() in setup.py). Add any other project
# information should go to pyproject.toml instead.
#
# TODO: migrate Babel options to pyproject.toml when it's better supported


[options]
packages = find:
namespace_packages = ckanext
install_requires =
    requests
include_package_data = True

[options.entry_points]
babel.extractors =
                 ckan = ckan.lib.extract:extract_ckan

[options.extras_require]

[extract_messages]
keywords = translate isPlural
add_comments = TRANSLATORS:
output_file = ckanext/series_explorer/i18n/ckanext-series_explorer.pot
width = 80

[init_catalog]
domain = ckanext-series_explorer
input_file = ckanext/series_explorer/i18n/ckanext-series_explorer.pot
output_dir = ckanext/series_explorer/i18n

[update_catalog]
domain = ckanext-series_explorer
input_file = ckanext/series_explorer/i18n/ckanext-series_explorer.pot
output_dir = ckanext/series_explorer/i18n
previous = true

[compile_catalog]
domain = ckanext-series_explorer
directory = ckanext/series_explorer/i18n
statistics = true
